nameOverride: null
fullnameOverride: null

image:
  registry: docker.io
  repository: andreziviani/aws-health-exporter
  # -- Overrides the image tag whose default is the chart's appVersion
  tag: null
  pullPolicy: IfNotPresent

imagePullSecrets: []

args: []

#env:
#  - name: SLACK_TOKEN
#    valueFrom:
#      secretKeyRef:
#        name: aws-health-exporter
#        key: SLACK_TOKEN
#  - name: SLACK_CHANNEL
#    valueFrom:
#      secretKeyRef:
#        name: aws-health-exporter
#        key: SLACK_CHANNEL

annotations: {}

updateStrategy:
  type: RollingUpdate

podLabels: {}

podAnnotations: {}
#  prometheus.io/scrape: "true"
#  prometheus.io/port: "http-metrics"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
#  limits:
#    cpu: 5m
#    memory: 20Mi

podPortName: http-metrics

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}
  labels: {}
  portName: http-metrics

serviceAccount:
  create: true
  name: null
  labels: {}
  #annotations:
  #  eks.amazonaws.com/role-arn: ...

serviceMonitor:
  enabled: false
  path: /metrics
  labels: {}
  interval: 30s
  scheme: http
  tlsConfig: {}
  scrapeTimeout: 30s
  relabelings: []

#nodeSelector: |
#  selector: label
#
#topologySpreadConstraints: |
#  - maxSkew: 1
#    topologyKey: topology.kubernetes.io/zone
#    whenUnsatisfiable: DoNotSchedule
#    labelSelector:
#      matchLabels:
#        {{- include "aws-health-exporter.selectorLabels" . | nindent 6 }}
#
#affinity: |
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchLabels:
#            {{- include "aws-health-exporter.selectorLabels" . | nindent 10 }}
#        topologyKey: kubernetes.io/hostname
#
#tolerations: |
#  - effect: NoSchedule
#    operator: Exists

podSecurityContext: {}

containerSecurityContext:
  privileged: false
  runAsUser: 1000
