apiVersion: v2
name: eks-cost-exporter
description: Exports the cost of each Kubernetes pod as prometheus metrics
type: application
appVersion: v0.4.0
version: 0.4.0
maintainers:
  - name: AndreZiviani
