apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-scaler.fullname" . }}
  labels:
    {{- include "az-scaler.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "az-scaler.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "az-scaler.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | indent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | indent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: az-scaler
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{ toYaml .Values.command }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      topologySpreadConstraints:
        {{- tpl (.Values.topologySpreadConstraints) . | nindent 8 }}
      nodeSelector:
        {{- tpl (.Values.nodeSelector) . | nindent 8 }}
      tolerations:
        {{- tpl (.Values.tolerations) . | nindent 8 }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (.Values.affinity) . | nindent 8 }}
      {{- end }}
