apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    {{- include "telnet-exporter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  telnet-exporter.yaml: |-
    {{ tpl .Values.config . | nindent 4 }}