apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telnet-exporter.fullname" . }}
  labels:
    {{- include "telnet-exporter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "telnet-exporter.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "telnet-exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | indent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "telnet-exporter.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: telnet-exporter
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.podPortName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app
              readOnly: true
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (.Values.topologySpreadConstraints) . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: config
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (.Values.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- tpl (.Values.tolerations) . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (.Values.affinity) . | nindent 8 }}
      {{- end }}
