nameOverride: null
fullnameOverride: null

image:
  registry: docker.io
  repository: andreziviani/ec2-price-exporter
  # -- Overrides the image tag whose default is the chart's appVersion
  tag: null
  pullPolicy: IfNotPresent

imagePullSecrets: []

args:
  - "-cache"
  - "3600"

annotations: {}

updateStrategy:
  type: RollingUpdate

podLabels: {}

podAnnotations: {}
#  prometheus.io/scrape: "true"
#  prometheus.io/port: "http-metrics"

priorityClassName: system-node-critical

resources:
  requests:
    cpu: 50m
    memory: 128Mi
#  limits:
#    cpu: 5m
#    memory: 20Mi

replicas: 1

podPortName: http-metrics

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}
  labels: {}
  portName: service

serviceAccount:
  create: true
  name: null
  labels: {}
  #annotations:
  #  eks.amazonaws.com/role-arn: ...

serviceMonitor:
  enabled: true
  path: /metrics
  labels: {}
  interval: 30s
  scheme: http
  tlsConfig: {}
  scrapeTimeout: 120s
  relabelings: []

#nodeSelector: |
#  selector: label
#
#topologySpreadConstraints: |
#  - maxSkew: 1
#    topologyKey: topology.kubernetes.io/zone
#    whenUnsatisfiable: DoNotSchedule
#    labelSelector:
#      matchLabels:
#        {{- include "ec2-pricing-exporter.selectorLabels" . | nindent 6 }}
#
#affinity: |
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchLabels:
#            {{- include "ec2-pricing-exporter.selectorLabels" . | nindent 10 }}
#        topologyKey: kubernetes.io/hostname
#
#tolerations: |
#  - effect: NoSchedule
#    operator: Exists

podSecurityContext: {}

containerSecurityContext:
  privileged: false
  runAsUser: 1000
