apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
stringData:
  agent.yaml: |
    server:
      {{- tpl .Values.agentServerConfig . | nindent 6 }}
    integrations:
      {{- tpl .Values.integrationsConfig . | nindent 6 }}
    {{- if .Values.prometheusDaemonSet.enabled }}
    metrics:
      {{- tpl .Values.prometheusDaemonSet.config . | nindent 6 }}
    {{- end }}
    {{- if .Values.loki.enabled }}
    logs:
      {{- tpl .Values.loki.config . | nindent 6 }}
    {{- end }}
    {{- if .Values.tempo.enabled }}
    traces:
      {{- tpl .Values.tempo.config . | nindent 6 }}
    {{- end }}
  agent-deployment.yaml: |
    {{- if .Values.prometheusDeployment.enabled }}
    server:
      {{- tpl .Values.agentServerConfig . | nindent 6 }}
    integrations:
      {{- tpl .Values.integrationsDeploymentConfig . | nindent 6 }}
    metrics:
      {{- tpl .Values.prometheusDeployment.config . | nindent 6 }}
    {{- end }}
  {{- if .Values.tempo.enabled }}
  strategies.json: |
    {{ .Values.tempo.strategies }}
  {{- end }}
