apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
stringData:
  agent.yaml: |
    server:
      {{- tpl .Values.agentServerConfig . | nindent 6 }}
    integrations:
      {{- tpl .Values.integrationsConfig . | nindent 6 }}
    {{- if .Values.prometheusDaemonSet.enabled }}
    prometheus:
      {{- tpl .Values.prometheusDaemonSet.config . | nindent 6 }}
    {{- end }}
    {{- if .Values.loki.enabled }}
    loki:
      {{- tpl .Values.loki.config . | nindent 6 }}
    {{- end }}
    {{- if .Values.tempo.enabled }}
    tempo:
      {{- tpl .Values.loki.config . | nindent 6 }}
    {{- end }}
  agent-deployment.yaml: |
    {{- if .Values.prometheusDeployment.enabled }}
    server:
      {{- tpl .Values.agentServerConfig . | nindent 6 }}
    integrations:
      {{- tpl .Values.integrationsConfig . | nindent 6 }}
    prometheus:
      {{- tpl .Values.prometheusDeployment.config . | nindent 6 }}
    {{- end }}
